name: 'Run trivy with reviewdog'
description: '🐶 Run trivy with reviewdog on pull requests'
author: 'yeap'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  trivy_image:
    description: 'Docker image to analyse with trivy'
    default: ''
  trivy_flags:
    description: 'Trivy flags. (trivy <trivy_flags>)'
    default: ''
  file_name:
    description: 'Reviewdog needs a file to attach any diagntostic'
    default: 'Dockerfile'
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'trivy'
  exclude:
    description: 'List of files and folders to exclude'
    default: ''
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is file.
    default: 'file'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  debug:
    descrition: 'Debug mode'
    dafault: 'false'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: sh
      env:
        REVIEWDOG_VERSION: v0.11.0
        TRIVY_VERSION: 0.15.0
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_EXCLUDE: ${{ inputs.exclude }}
        INPUT_TRIVY_FLAGS: ${{ inputs.trivy_flags }}
        INPUT_TRIVY_IMAGE: ${{ inputs.trivy_image }}
        INPUT_FILE_NAME: ${{ inputs.file_name }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_DEBUG: ${{ inputs.debug }}
branding:
  icon: 'check-circle'
  color: 'blue'
