name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-check:
    name: trivy + reviewdog - old debian
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          trivy_image: "debian:buster-20201209"
          trivy_flags: "--ignore-unfixed"
          debug: "true"
          filter_mode: "nofilter"
  test-check-nodebug:
    name: trivy + reviewdog - empty no debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          trivy_image: "debian"
          trivy_flags: "--ignore-unfixed"
          filter_mode: "nofilter"
  test-check-empty:
    name: trivy + reviewdog - empty debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          trivy_image: "debian"
          trivy_flags: "--ignore-unfixed"
          debug: "true"
          filter_mode: "nofilter"
  test-check-review:
    name: trivy + reviewdog - review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          trivy_image: "debian:buster-20201209"
          trivy_flags: "--ignore-unfixed"
          filter_mode: "nofilter"
          reporter: "github-pr-review"
