name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-check:
    name: trivy + reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          trivy_image: debian:buster-20201209
          trivy_flags: "--ignore-unfixed"
          debug: "true"
          level: "info"
